name: Terraform CI

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Validation
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: MCS-LAB/INFRA_MONITORING/environments/dev

    steps:

      # 1. Checkout repository
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # 3. Check formatting
      - name: Terraform Format
        run: terraform fmt -check -recursive

      # 4. Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # 5. Validate Terraform configuration
      - name: Terraform Validate
        run: terraform validate

      # 6. Generate Terraform plan
      - name: Terraform Plan
        run: terraform plan